name: ci - gfortran - latest version

on:
  push:
    branches:
      - '5.3*'
  pull_request:
    branches:
      - '5.3*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9

    - name: Setup symbolic links on Linux
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
        sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
        sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

    - name: Setup symbolic link to gfortran on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo ln -fs /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        sudo ln -fs /usr/local/bin/gcc-10 /usr/local/bin/gcc
        sudo ln -fs /usr/local/bin/g++-10 /usr/local/bin/g++

    - name: Print GNU compiler versions
      run: |
        gfortran --version
        gcc --version
        g++ --version

    - name: Install python packages
      run: |
        .github/common/install-python-std.sh

    - name: Set and print branch name
      run: |
        .github/common/git-branch-export.sh

    - name: Setup prms
      run: |
        meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin

    - name: Meson Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        directory: builddir
        action: build
        setup-options: builddir -Ddebug=false --prefix=$(pwd) --libdir=bin

    - name: Meson Install
      uses: BSFishy/meson-build@v1.0.3
      with:
        directory: builddir
        action: install

    - name: Test for build success
      working-directory: ./.github/common
      run: |
        python prms_build_check.py
